Repository SOPT-29th-Joint-Seminar-10/Client-iOS, pull requests merged in 2021-11, with the labels that each got.

#4 Feature/#2
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue010.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue020.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue030.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue040.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue050.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue060.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue070.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/blue080.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray005.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray010.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray020.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray030.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray040.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray050.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray060.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray070.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/gray080.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/navy050.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/navy060.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/red050.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/whtie.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/yellow050.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Assets.xcassets/yellow060.colorset/Contents.json
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Extension/UIColorPlusExtension.swift
Labels: ➕ADD, 🌱 빈

#7 ✅[CHORE] 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/ios-----issue-template.md
Labels: ✅ CHORE

#9 ✨[FEAT] 탭바생성
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Constants/Const.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Constants/Storyboard.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Constants/TempConstants.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Constants/ViewController.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Constants/Xib.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Info.plist
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Base.lproj/Main.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Base.lproj/MainTab.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/CellTemp.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/RecommendCarCVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/RecommendCarCVC.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/ReservationCVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/ReservationCVC.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Extension/CALayer+Extension.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/SceneDelegate.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/CarPlanVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/HomeVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/MainTabVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/MyPageVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/PairingVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/ViewController.swift
Labels: ✨FEAT, 🤓 뀨

#13 ✨[FEAT] 차량 예약 셀, 추천 차량 셀 구현 및 탭바 iOS 13 대응(#10)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Base.lproj/MainTab.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/AppModel/RecommendCarModel.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/AppModel/ReservationCarModel.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/AppModel/TempAppModel.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/RecommendCarCVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/RecommendCarCVC.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/ReservationCVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/ReservationCVC.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/MainTabVC.swift
Labels: ✨FEAT

#16 ✨[FEAT] 차량 예약 커스텀 뷰 구현(#11)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/AppModel/RecommendCarModel.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/View/ReservationHistoryView/ReservationHistoryView.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/View/ReservationHistoryView/ReservationHistoryView.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/View/TempView.swift
Labels: ✨FEAT, 🤓 뀨

#20 ✨[FEAT] MainTab - Filter 스토리보드 연결(#19)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Base.lproj/MainTab.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/CarPlanVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/MainTabVC.swift
Labels: ✨FEAT, 🌱 빈

#22 ✨[FEAT] 필터 세부 기능 구현(UI) (#15)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Filter.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/FilterCVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/FilterCVC.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/FilterVC.swift
Labels: ✨FEAT, 🌱 빈

#21 [FEAT] 홈 화면 UI 구성2(#12)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Base.lproj/MainTab.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/AppModel/RecommendCarModel.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/RecommendCarCVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/View/ReservationHistoryView/ReservationHistoryView.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/View/ReservationHistoryView/ReservationHistoryView.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/CarPlanVC.swift
Labels: question, ✅ CHORE, 희

#26 ✨[FEAT] 네비게이션바 커스텀 및 FilterVC 컬렉션뷰 레이아웃 수정 (#24)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Filter.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/FilterCVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Cell/FilterCVC.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/FilterVC.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/MainTabVC.swift
Labels: ✨FEAT, 🌱 빈

#28 ✨[FEAT] 예약목록 스택뷰와 부분 수정 (#27)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Storyboards/Base.lproj/MainTab.storyboard
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/View/ReservationHistoryView/ReservationHistoryView.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/View/ReservationHistoryView/ReservationHistoryView.xib
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/CarPlanVC.swift
Labels: ✅ CHORE, ✨FEAT

#35 ✨[FEAT] 나의 예약 API 연결 (#32)
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Resource/Constants/APIConstants.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/Extension/Dictionary+Extension.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/NetworkModel/ReservationResponseData.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/NetworkService/ReservationService.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/NetworkService/TempUserSignService.swift
  SOPT-29th-JointSeminar10-iOS/SOPT-29th-JointSeminar10-iOS/Source/ViewController/Tabar/CarPlanVC.swift
Labels: ✨FEAT
